/**
 * @description URL파라미터 관련 정수 클래스
 */
public class ConstUrlParameter {

    /**
     * @description 이전 화면의 URL 파라미터명
     */
    public static final String PARAM_NAME_RET_URL = 'retUrl';

    /**
     * @description 저장 후 되돌아갈 화면의 URL 파라미터명
     */
    public static final String PARAM_NAME_SAVE_URL = 'saveUrl';

    /**
     * @description 도서 ID의 URL 파라미터명
     */
    public static final String PARAM_NAME_BOOK_ID = 'bookId';

    /**
     * @description 회원 ID의 URL 파라미터명
     */
    public static final String PARAM_NAME_MEMBER_ID = 'memberId';
}